### ISSUE TITLE
A more granulated run isntructions

### ISSUE THREAD

**Issue by yanko** [roysanchez/ServForOracle#3]
I cant seem to fin the Oracle.DataAccess (4.112.3) nuget pkg, I am new to the world of .net and nuget. could you point me to the right direction please?

also I am using the oracle 18 (ODAC183_x64).

iI also get this
">C:\Users\yanko\dev\visual-studio\ServForOracle\ServForOracle\ServForOracle.csproj : warning NU1604: Project dependency Oracle.DataAccess does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
1>"

thank you

**Comment by roysanchez** [comment]
Hi @yanko,

Sadly Oracle does not provide nuget packages for the native ODAC library, your only option is to create an account and download it.

You can find it on this link http://www.oracle.com/technetwork/topics/dotnet/downloads/odacdeploy-4242173.html

**Comment by yanko** [comment]
hi @roysanchez 
sorry to bug you mane, but I am having issues installing ODAC 19c on windows 10.
keeps giving me this error:

PRVG-1901 : failed to setup CVU remote execution framework directory "C:\Users\ME\AppData\Local\Temp\CVU_19.0.0.0.0_ME\" on nodes "HOSTNAME "
Please select a different work area for the framework
HOSTNAME : PRKN-1040 : Failed to remove directory "C:\Users\JPETRO~1\AppData\Local\Temp\\oraremservicev2\" on node "HOSTNAME " 
 Access is denied.

I cant seem to find any information anywhere.
could you please tell me if I am doing anything wrong, I am choosing all the default setting.

thank you.
